import type { Metadata } from "next";
import "./globals.css";
import { Fira_Sans } from 'next/font/google';

const fira_sans= Fira_Sans({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // customize as needed
  variable: '--font-blinker',
});

export const metadata: Metadata = {
  icons:{
    icon: "/logo.svg",
    shortcut: "/logo.svg",
    apple: "/logo.svg",
  },
  title: "Haera's Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={fira_sans.className}
      >
        {children}
      </body>
    </html>
  );
}
